// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoiSc1NwZHvLFLA375uQ1lUL8nUCJ8G78',
    appId: '1:825783729440:web:d6d52aa1b0c52ceec02b45',
    messagingSenderId: '825783729440',
    projectId: 'vital-code-478705-n5',
    authDomain: 'vital-code-478705-n5.firebaseapp.com',
    storageBucket: 'vital-code-478705-n5.firebasestorage.app',
    measurementId: 'G-FKV0TYV1MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0_VF_lHToydRUZvEL1b2S3PswmvoYuo',
    appId: '1:825783729440:android:c5ced6524bcb5bacc02b45',
    messagingSenderId: '825783729440',
    projectId: 'vital-code-478705-n5',
    storageBucket: 'vital-code-478705-n5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_ngvYRbpMVD0JKCR_INPVreROu28jd8',
    appId: '1:825783729440:ios:4985acce08ca3e30c02b45',
    messagingSenderId: '825783729440',
    projectId: 'vital-code-478705-n5',
    storageBucket: 'vital-code-478705-n5.firebasestorage.app',
    iosBundleId: 'com.example.nuliApp',
  );
}
